# WARNING: this google app engine deployment method is from the original lzeke0/TwitchRSS repo from which this repo was forked
# it should tecnically work, but it's untested and not supported for this repo
runtime: python38

entrypoint: gunicorn -b :$PORT -k gthread --threads 2 twitchrss:app

env_variables:
  TWITCH_CLIENT_ID: __INSERT_TWITCH_CLIENT_ID_HERE__
  TWITCH_SECRET: __INSERT_TWITCH_SECRET_HERE__

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index\.html

- url: /.+
  script: auto

automatic_scaling:
  max_instances: 1
