name: deploy to dockerhub
on:
  workflow_dispatch:

jobs:
  push_to_Docker_Hub_amd64:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: Bump patch version
          run: |
            # Get the current version
            VERSION=v2.1.2
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-amd64,${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-amd64
            platforms: linux/amd64
  push_to_Docker_Hub_arm64:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: Bump patch version
          run: |
            # Get the current version
            VERSION=v2.1.2
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-arm64,${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-arm64
            platforms: linux/arm64
  push_to_Docker_Hub_arm_v7:
      runs-on: ubuntu-latest
      steps:
        - name: Set Swap Space
          uses: pierotofy/set-swap-space@v1.0
          with:
            swap-size-gb: 10
        - run: |
            # Workaround for https://github.com/rust-lang/cargo/issues/8719
            sudo mkdir -p /var/lib/docker
            sudo mount -t tmpfs -o size=10G none /var/lib/docker
            sudo systemctl restart docker
        - name: checkout repo
          uses: actions/checkout@v3
        - name: get version
          run: |
            # Get the current version
            VERSION=v2.1.2
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-armv7,${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-armv7
            platforms: linux/arm/v7
  merge_tags:
      needs: [push_to_Docker_Hub_arm64, push_to_Docker_Hub_arm_v7, push_to_Docker_Hub_amd64]
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: get version
          run: |
            # Get the current version
            VERSION=v2.1.2
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: merge into latest
          run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-armv7 ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-arm64 ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:latest-amd64
        - name: merge into versio
          run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-armv7 ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-arm64 ${{ secrets.DOCKERHUB_USERNAME }}/twitch_to_podcast_rss:${{ env.VERSION }}-amd64
